CREATE TABLE tracks(
id INTEGER PRIMARY KEY AUTOINCREMENT,
title VARCHAR,
artist VARCHAR,
length TIME,
genre_id  VARCHAR);

CREATE TABLE all_genre(
id INTEGER PRIMARY KEY AUTOINCREMENT,
genre VARCHAR)



